### ISSUE TITLE
Does not run on Ubuntu 18.04

### ISSUE THREAD

**Issue by probonopd** [Eroica/Paletti#1]
Hi, thanks for making an AppImage.
However, the current one does not run on Ubuntu 18.04.

Please compile on the oldest still-supported LTS release, which is currently Ubuntu xenial, thanks.

More information:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#creating-appimages-that-are-compatible-with-many-systems

```
/run/firejail/appimage/.appimage-9144/AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/firejail/appimage/.appimage-9144/usr/bin/../lib/libgtk-3.so.0)
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/1995

**Comment by Eroica** [comment]
Hi there,

I think I was able to set up a Travis CI that builds Paletti on Ubuntu 16.04 ("xenial"). By the way, you wrote both 18.04 (which is "bionic") and "xenial" (which is 16.04). Which LTS version do you recommend to build on?

In any case, I chose the older one for now. Funny to see the old GTK theme if I run this on my machine, but I guess that's just how it works. I think I will just offer several versions of AppImage builds with a note that the "default" AppImage will run on something as old as Ubuntu 16.04, but there are also builds for newer distributions. Or do you have any other recommendations on this topic?

AppImage is the only sane way of packaging applications for GNU/Linux. Thank you for your work.

**Comment by probonopd** [comment]
Hi, thanks for your response. As I wrote above, please always compile on the _oldest still-supported LTS_ release, which is currently Ubuntu xenial. If you do this, then it should run on systems like my bionic one as well.

> there are also builds for newer distributions

Why? To make Gtk took better?

>  Or do you have any other recommendations on this topic?

My recommendation is always to develop against the _oldest still-supported LTS_ because that is the "minimum common denominator" that one can reasonably assume to be "everywhere" at this point.

If that is not desired, one could try to privately bundle _everything_ (including Gtk and possibly more) like e.g., Inkscape does.

**Comment by probonopd** [comment]
Thank you, it is working for me now.
